Repository florinres/MicroCISC, pull requests merged in 2025-09, with the labels that each got.

#87 Added new file function, fixed some colors on front-end window microp…
  Ui/App.xaml
  Ui/Interfaces/Services/ICpuService.cs
  Ui/Interfaces/ViewModel/IActionsBarViewModel.cs
  Ui/Services/CpuService.cs
  Ui/Ui.csproj
  Ui/ViewModels/Components/MenuBar/MenuBarViewModel.cs
  Ui/ViewModels/Components/Microprogram/MicroprogramViewModel.cs
  Ui/ViewModels/Components/Static_Messages.Designer.cs
  Ui/ViewModels/Components/Static_Messages.resx
  Ui/ViewModels/Generics/ActionsBarViewModel.cs
  Ui/Views/UserControls/Microprogram/MicroprogramControl.xaml
  Ui/Views/Windows/MainWindow.xaml
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: bug

#128 bug: Fix weird zoom behavior
  Ui/App.xaml
  Ui/Interfaces/Services/ICpuService.cs
  Ui/Interfaces/ViewModel/IActionsBarViewModel.cs
  Ui/Services/CpuService.cs
  Ui/Ui.csproj
  Ui/ViewModels/Components/MenuBar/MenuBarViewModel.cs
  Ui/ViewModels/Components/Microprogram/MicroprogramViewModel.cs
  Ui/ViewModels/Components/Static_Messages.Designer.cs
  Ui/ViewModels/Components/Static_Messages.resx
  Ui/ViewModels/Generics/ActionsBarViewModel.cs
  Ui/Views/UserControls/Diagram/DiagramUserControl.xaml
  Ui/Views/UserControls/Diagram/DiagramUserControl.xaml.cs
  Ui/Views/UserControls/Microprogram/MicroprogramControl.xaml
  Ui/Views/Windows/MainWindow.xaml
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: bug

#129 feature: Improve the design of diagram
  Ui/Interfaces/ViewModel/IDiagramViewModel.cs
  Ui/ViewModels/Components/Diagram/DiagramViewModel.cs
  Ui/ViewModels/Components/Diagram/HighlightableConnectorViewModel.cs
  Ui/Views/UserControls/Diagram/Components/SumBlock.xaml
  Ui/Views/UserControls/Diagram/Components/SumBlock.xaml.cs
  Ui/Views/UserControls/Diagram/DiagramUserControl.xaml
  Ui/Views/UserControls/Diagram/DiagramUserControl.xaml.cs
Labels: enhancement

#135 feature: Added logic for changing number base
  Ui/ViewModels/Components/HexViewer/HexViewModel.cs
  Ui/Views/UserControls/Hex/HexControl.xaml
Labels: enhancement

#139 fix: Updated logic for hiding the Tools windows
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: bug

#145 Ui improvements and bug fixes
  MainMemory.Business/Models/MemoryContentWrapper.cs
  Ui/Assets/AvalonEdit/Assembly16BitHighlighting-Dark.xshd
  Ui/Assets/AvalonEdit/Assembly16BitHighlighting-Light.xshd
  Ui/Components/StyledAvalonEdit.cs
  Ui/Helpers/AvalonEditHelper.cs
  Ui/Helpers/ThemeToIconConverter.cs
  Ui/Helpers/ThemeToIndexConverter.cs
  Ui/Helpers/ThemeToToggleConverter.cs
  Ui/Interfaces/ViewModel/IActionsBarViewModel.cs
  Ui/Interfaces/ViewModel/IHexViewModel.cs
  Ui/Resources/ThemeBrushes.xaml
  Ui/Services/AssemblerService.cs
  Ui/Services/CpuService.cs
  Ui/Services/DockingService.cs
  Ui/Ui.csproj
  Ui/ViewModels/Components/HexViewer/HexViewModel.cs
  Ui/ViewModels/Components/MenuBar/MenuBarViewModel.cs
  Ui/ViewModels/Generics/ActionsBarViewModel.cs
  Ui/ViewModels/Generics/FileViewModel.cs
  Ui/Views/UserControls/Hex/GoToAddressDialog.xaml
  Ui/Views/UserControls/Hex/GoToAddressDialog.xaml.cs
  Ui/Views/UserControls/Hex/HexControl.xaml
  Ui/Views/UserControls/Hex/HexControl.xaml.cs
  Ui/Views/UserControls/Microprogram/MicroprogramControl.xaml
  Ui/Views/Windows/MainWindow.xaml
  Ui/Views/Windows/MainWindow.xaml.cs
  Ui/Views/Windows/TestHexWindow.xaml
  Ui/Views/Windows/TestHexWindow.xaml.cs
Labels: bug, enhancement

#149 feature: Make alu and flag bits update text when stepping
  Ui/ViewModels/Components/Diagram/DiagramViewModel.cs
  Ui/Views/UserControls/Diagram/Components/SumBlock.xaml
Labels: enhancement

#162 fix: Fix PC not returning to User_Code from IRQ
  Assembler.Business/Assembler.cs
  Assembler.Business/Encoder.cs
  Ui/Helpers/HighlightCurrentLineBackgroundRenderer.cs
  Ui/Interfaces/Services/IAssemblerService.cs
  Ui/Interfaces/Services/ICpuService.cs
  Ui/Models/MemorySection.cs
  Ui/Services/AssemblerService.cs
  Ui/Services/CpuService.cs
  Ui/ViewModels/Components/MenuBar/MenuBarViewModel.cs
  Ui/ViewModels/Generics/FileViewModel.cs
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: bug

#164 feature: Show only 36 bits for MIR registers instead of 64
  Ui/Helpers/RegisterFormatConverter.cs
  Ui/Views/UserControls/Diagram/Components/RegisterBlock.xaml
Labels: enhancement

#178 176 UI make run button work only after having assembled the code
  Ui/Interfaces/ViewModel/IActionsBarViewModel.cs
  Ui/ViewModels/Generics/ActionsBarViewModel.cs
  Ui/Views/Windows/MainWindow.xaml
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: enhancement

#177 trivial: Set cursor at first micro-command for instruction step
  Ui/Services/CpuService.cs
Labels: bug

#180 feature: Display buses value on UI
  Ui/Interfaces/ViewModel/IDiagramViewModel.cs
  Ui/Services/CpuService.cs
  Ui/ViewModels/Components/Diagram/DiagramViewModel.cs
  Ui/Views/UserControls/Diagram/Components/BusValues.xaml
  Ui/Views/UserControls/Diagram/Components/BusValues.xaml.cs
  Ui/Views/UserControls/Diagram/DiagramUserControl.xaml
Labels: enhancement

#171 153 editor create dark and light theme for syntax highlighting
  Ui/Assets/AvalonEdit/Assembly16BitHighlighting-Dark.xshd
  Ui/Assets/AvalonEdit/Assembly16BitHighlighting-Light.xshd
Labels: enhancement

#188 175 UI fix muliple source files open bug
  Ui/Components/StyledAvalonEdit.cs
  Ui/Services/CpuService.cs
  Ui/ViewModels/Components/MenuBar/MenuBarViewModel.cs
  Ui/ViewModels/Generics/ActionsBarViewModel.cs
  Ui/ViewModels/Generics/FileViewModel.cs
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: bug, enhancement

#191 fix: Removed buggy loading of the least recently used layout
  Ui/Interfaces/Services/IDockingService.cs
  Ui/Services/DockingService.cs
  Ui/Services/DummyDockingService.cs
  Ui/ViewModels/Components/MenuBar/MenuBarViewModel.cs
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: bug
