Repository florinres/MicroCISC, pull requests merged in 2025-08, with the labels that each got.

#58 Create tests for instructions
  CISCraft.sln
  CPU.Business/CPU.cs
  CPU.Business/Models/GPR.cs
  CPU.Business/Models/REGISTERS.cs
  CPU.Main/Program.cs
  CPU.Tests/B1InstructionsTests.cs
  CPU.Tests/B2InstructionsTests.cs
  CPU.Tests/B3InstructionsTests.cs
  CPU.Tests/B4nstructionsTests.cs
  CPU.Tests/CPU.Tests.csproj
  CPU.Tests/CPU.Tests.sln
  CPU.Tests/CpuTestsUtils.cs
Labels: enhancement

#61 Created a tool to convert the excel with microcommands into our suppo…
  Tools/Input/microprogram.xlsx
  Tools/convert_to_json.py
Labels: enhancement

#67 Fix: updated code so that we can build the entire solution
  .gitignore
  CPU.Business/CPU.Business.sln
  CPU.Business/Models/GPR.cs
  CPU.Main/Program.cs
  CPU.Tests/B1InstructionsTests.cs
  CPU.Tests/CpuTestsUtils.cs
  MainMemory.BusinessTests/MainMemoryTests.cs
Labels: bug

#74 Small fixes: Improve tests and fix instructions
  Assembler.Business/Encoder.cs
  CPU.Business/CPU.cs
  CPU.Tests/B1InstructionsTests.cs
  CPU.Tests/B2InstructionsTests.cs
  CPU.Tests/B3InstructionsTests.cs
  CPU.Tests/B4nstructionsTests.cs
  CPU.Tests/CpuTestsUtils.cs
Labels: bug, enhancement

#76 Renamed codDefault to an english name and added it to build output
  Ui/Assets/default_code.txt
  Ui/Ui.csproj
  Ui/ViewModels/Components/MenuBar/MenuBarViewModel.cs
Labels: bug

#79 fix: Prevent halt test from stalling builds
  CPU.Tests/B4nstructionsTests.cs
Labels: bug

#81 Quickfix/comply flags with documentation
  CPU.Business/CPU.cs
  CPU.Business/ControlUnit.cs
  Configs/MPM.json
Labels: bug

#82 69 testing test b1 instructions
  CPU.Business/CPU.cs
  CPU.Tests/B1InstructionsTests.cs
  CPU.Tests/B2InstructionsTests.cs
  CPU.Tests/B3InstructionsTests.cs
  CPU.Tests/B4nstructionsTests.cs
  CPU.Tests/CpuTestsUtils.cs
Labels: enhancement

#97 feature: Added CI/CD job for generating releases
  .github/workflows/genereate_release.yaml
  .gitignore
  Ui/Ui.csproj
Labels: enhancement

#99 88 UI highlight rows when stepping at instruction level
  Ui/App.xaml.cs
  Ui/Helpers/HighlightCurrentLineBackgroundRenderer.cs
  Ui/Interfaces/Services/ICpuService.cs
  Ui/Interfaces/ViewModel/IActionsBarViewModel.cs
  Ui/Services/CpuService.cs
  Ui/ViewModels/Generics/ActionsBarViewModel.cs
  Ui/ViewModels/Generics/FileViewModel.cs
  Ui/Views/Windows/MainWindow.xaml
  Ui/Views/Windows/MainWindow.xaml.cs
Labels: enhancement

#106 Test b3 instructions
  Assembler.Business/CiscGrammar.cs
  Assembler.Business/Encoder.cs
  CPU.Business/CPU.cs
  CPU.Business/ControlUnit.cs
  CPU.Tests/B2InstructionsTests.cs
  CPU.Tests/B3InstructionsTests.cs
  CPU.Tests/B4nstructionsTests.cs
  CPU.Tests/CpuTestsUtils.cs
  Configs/MPM.json
  Ui/Services/CpuService.cs
Labels: bug, enhancement
